[toolchain]
package_manager = "pnpm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
panda_monopoly = "4vucUqMcXN4sgLsgnrXTUC9U7ACZ5DmoRBLbWt4vrnyR"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm exec ts-mocha -p ./tsconfig.json -t 1000000 tests/roll-dice.test.ts"
