import type { Metadata } from "next";
import {
  // Geist,
  // Geist_Mono,
  // JetBrains_Mono,
  // Instrument_Serif,
  // Instrument_Sans,
  // Urbanist,
  // Bricolage_Grotesque,
  // Oswald,
  // Cherry_Bomb_One,
  Space_Grotesk,
} from "next/font/google";
import "@/styles/globals.css";
import { Toaster } from "@/components/ui/sonner";
// import "@/styles/fonts.css";
// import "@/styles/monopoly.css";
import RootProviders from "@/providers";

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  display: "swap", // Better font loading performance
  preload: true,
  variable: "--font-space-grotesk",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={spaceGrotesk.className}
        // className={cn(
        //   geistSans.variable,
        //   geistMono.variable,
        //   jetBrainsMono.variable,
        //   instrumentSerif.variable,
        //   instrumentSans.variable,
        //   urbanist.variable,
        //   bricolageGrotesque.variable,
        //   oswald.variable,
        //   cherryBombOne.variable,
        //   "antialiased font-sans"
        // )}
      >
        <RootProviders>{children}</RootProviders>
        <Toaster />
      </body>
    </html>
  );
}
